export const medicineTheme = {
  pageBg: "var(--medicine-page-bg)",
  heroGradient:
    "linear-gradient(180deg, var(--medicine-hero-start) 0%, var(--medicine-hero-end) 100%)",
  ctaGradient:
    "linear-gradient(135deg, var(--medicine-primary-ink) 0%, var(--medicine-primary-dark) 45%, var(--medicine-primary) 100%)",
  brandGradient:
    "linear-gradient(135deg, var(--medicine-primary-hover) 0%, var(--medicine-primary) 100%)",
  surface: "var(--medicine-surface)",
  surfaceSoft: "var(--medicine-surface-soft)",
  surfaceAccent: "var(--medicine-surface-accent)",
  primary: "var(--medicine-primary)",
  primaryHover: "var(--medicine-primary-hover)",
  primaryDark: "var(--medicine-primary-dark)",
  primaryInk: "var(--medicine-primary-ink)",
  primarySoft: "var(--medicine-primary-soft)",
  text: "var(--medicine-text)",
  textSoft: "var(--medicine-text-soft)",
  textMuted: "var(--medicine-text-muted)",
  textFaint: "var(--medicine-text-faint)",
  border: "var(--medicine-border)",
  borderStrong: "var(--medicine-border-strong)",
  blue: "var(--medicine-blue)",
  blueSoft: "var(--medicine-blue-soft)",
  orange: "var(--medicine-orange)",
  orangeSoft: "var(--medicine-orange-soft)",
  success: "var(--medicine-success)",
  successSoft: "var(--medicine-success-soft)",
  warning: "var(--medicine-warning)",
  warningSoft: "var(--medicine-warning-soft)",
  danger: "var(--medicine-danger)",
  dangerSoft: "var(--medicine-danger-soft)",
  shadowSm: "var(--medicine-shadow-sm)",
  shadowMd: "var(--medicine-shadow-md)",
  shadowLg: "var(--medicine-shadow-lg)",
  ring: "var(--medicine-ring)",
};
