import { createContext, useContext, useCallback, useMemo } from "react";
import { useTranslation } from "react-i18next";

export const translations = {
    ar: {
        dir: "rtl",
        // Navbar
        nav_home: "الرئيسية",
        nav_doctors: "الأطباء",
        nav_ai: "استشارات AI",
        nav_pharmacy: "الصيدلية",
        nav_articles: "المقالات",
        nav_contact: "تواصل",
        nav_login: "تسجيل الدخول",
        nav_register: "إنشاء حساب",
        brand: "ميدورا",

        // Hero
        hero_title: "ميدورا - منصتك الطبية الشاملة",
        hero_subtitle: "احجز موعدك مع أفضل الأطباء، ابحث عن الأدوية، واحصل على استشارات طبية فورية",
        hero_start: "ابدأ الآن",
        hero_learn: "اعرف المزيد",
        hero_card1_title: "استشارات AI",
        hero_card1_desc: "استشارات طبية فورية على مدار الساعة",
        hero_card2_title: "صيدليات موثوقة",
        hero_card2_desc: "شبكة واسعة من الصيدليات المعتمدة",
        hero_card3_title: "أطباء معتمدون",
        hero_card3_desc: "أكثر من 500 طبيب في مختلف التخصصات",
        hero_card4_title: "مقالات طبية",
        hero_card4_desc: "محتوى صحي مبسط يساعدك على اتخاذ قرارات أفضل",

        // Services
        services_title: "خدماتنا الطبية المتكاملة",
        services_sub: "نوفر لك مجموعة شاملة من الخدمات الطبية الرقمية لتسهيل رحلتك العلاجية",
        services_learnmore: "اعرف المزيد ←",
        svc1_title: "احجز موعد", svc1_desc: "احجز موعدك مع الأطباء بسهولة وسرعة",
        svc2_title: "استشارة AI", svc2_desc: "احصل على استشارة طبية فورية من ذكاء اصطناعي",
        svc3_title: "ابحث عن دواء", svc3_desc: "ابحث عن الأدوية والصيدليات القريبة منك",
        svc4_title: "ابحث عن طبيب", svc4_desc: "اعثر على أفضل الأطباء في تخصصات مختلفة",
        service_hub_seo_title: "الخدمات",
        service_hub_seo_description: "استكشف خدمات ميدورا الطبية: الأطباء، الأدوية، الصيدليات، الاستشارات الذكية، والمقالات الصحية.",
        service_hub_badge: "كل خدماتك الطبية في مكان واحد",
        service_hub_title: "اختر الخدمة الطبية التي تحتاجها الآن",
        service_hub_subtitle: "تنقّل بسرعة بين حجز الأطباء، البحث عن الدواء، الصيدليات القريبة، الاستشارات الذكية، والمحتوى الطبي الموثوق.",
        service_hub_section_title: "خدمات ميدورا",
        service_hub_available: "متاح",
        service_hub_doctor_title: "الأطباء والحجوزات",
        service_hub_doctor_desc: "ابحث عن الطبيب المناسب حسب التخصص والموقع واحجز موعدك بخطوات بسيطة.",
        service_hub_doctor_action: "ابحث عن طبيب",
        service_hub_medicine_title: "البحث عن الدواء",
        service_hub_medicine_desc: "اعرف تفاصيل الأدوية، البدائل، والتحذيرات، ثم اختر طريقة الحصول عليها.",
        service_hub_medicine_action: "ابحث عن دواء",
        service_hub_pharmacy_title: "الصيدليات القريبة",
        service_hub_pharmacy_desc: "استعرض الصيدليات المتاحة حولك وتحقق من توفر الأدوية وخيارات الاستلام أو التوصيل.",
        service_hub_pharmacy_action: "استعرض الصيدليات",
        service_hub_ai_title: "الاستشارة الذكية",
        service_hub_ai_desc: "اطرح أسئلتك الصحية واحصل على إرشاد أولي يساعدك على فهم الخطوة التالية.",
        service_hub_ai_action: "ابدأ الاستشارة",
        service_hub_articles_title: "المقالات الطبية",
        service_hub_articles_desc: "اقرأ مقالات صحية مبسطة عن الوقاية والعادات اليومية والرعاية الطبية.",
        service_hub_articles_action: "اقرأ المقالات",
        service_hub_guide_title: "لست متأكدًا من أين تبدأ؟",
        service_hub_guide_subtitle: "اختر الحالة الأقرب لك وسنوجهك للمسار الأنسب داخل ميدورا.",
        service_hub_guide_symptoms_title: "لديك أعراض وتحتاج لطبيب",
        service_hub_guide_symptoms_desc: "ابدأ بالبحث عن طبيب حسب التخصص أو المنطقة واحجز أقرب موعد.",
        service_hub_guide_medicine_title: "تبحث عن دواء أو بديل",
        service_hub_guide_medicine_desc: "استخدم البحث لمعرفة تفاصيل الدواء والصيدليات التي توفره.",
        service_hub_guide_question_title: "لديك سؤال طبي سريع",
        service_hub_guide_question_desc: "استخدم الاستشارة الذكية للحصول على إرشاد أولي قبل زيارة الطبيب.",
        service_hub_emergency_title: "تنبيه مهم",
        service_hub_emergency_desc: "في حالات الطوارئ أو الأعراض الخطيرة، تواصل فورًا مع الطوارئ أو اذهب لأقرب مستشفى. خدمات ميدورا لا تغني عن الرعاية العاجلة.",

        // HowItWorks
        how_title: "كيف تعمل ميدورا؟",
        how_sub: "أربع خطوات بسيطة للحصول على الرعاية الطبية التي تحتاجها",
        step1_title: "إنشاء حساب", step1_desc: "سجل كـمريض، طبيب، أو صيدلي في دقائق معدودة",
        step2_title: "ابحث واختر", step2_desc: "ابحث عن الطبيب المناسب أو الدواء الذي تحتاجه",
        step3_title: "احجز موعدك", step3_desc: "احجز مواعيدك الطبية بسهولة واحصل على تأكيد فوري",
        step4_title: "احصل على الرعاية", step4_desc: "استمتع بخدمة طبية متميزة وآمنة",

        // Stats
        stats_title: "أرقامنا تتحدث عن نفسها",
        stats_sub: "نفخر بثقة آلاف المستخدمين في خدماتنا الطبية المتميزة",
        stat1_label: "موعد ناجح",
        stat2_label: "مستخدم راضٍ",
        stat3_label: "صيدلية موثوقة",
        stat4_label: "طبيب معتمد",

        // Testimonials
        test_title: "ماذا يقول عملاؤنا؟",
        test_sub: "آراء حقيقية من مستخدمينا الكرام حول تجربتهم مع ميدورا",
        t1_name: "سيف واجد", t1_role: "مستخدم",
        t1_text: "منصة رائعة لتسهيل حجز المواعيد مع الأطباء. الخدمة ممتازة والتطبيق سهل الاستخدام جدًا.",
        t2_name: "ملك محمد", t2_role: "طبيبة أطفال",
        t2_text: "ميدورا ساعدتني كثيرًا في تنظيم مواعيدي والتواصل مع المرضى بشكل أفضل. أداة لا غنى عنها.",
        t3_name: "د. خالد أحمد", t3_role: "مدير",
        t3_text: "أنظمة الحجز وإدارة البيانات ممتازة، والتواصل مع العملاء رائع. زادت مبيعاتنا بشكل ملحوظ.",

        // CTA
        cta_title: "ابدأ رحلتك الصحية اليوم",
        cta_sub: "انضم إلى آلاف المستخدمين الذين يثقون في ميدورا للحصول على أفضل رعاية طبية",
        cta_login: "تسجيل الدخول",
        cta_register: "إنشاء حساب",

        // Footer
        footer_desc: "منصتك الطبية الشاملة للحصول على أفضل رعاية صحية رقمية",
        footer_quick: "روابط سريعة",
        footer_home: "الرئيسية",
        footer_find_doctor: "ابحث عن طبيب",
        footer_find_medicine: "ابحث عن دواء",
        footer_ai: "استشارة AI",
        footer_users: "للمستخدمين",
        footer_reg_patient: "إنشاء حساب (مريض)",
        footer_reg_doctor: "إنشاء حساب (طبيب)",
        footer_reg_pharmacy: "إنشاء حساب (صيدلي)",
        footer_login: "تسجيل الدخول",
        footer_contact: "تواصل معنا",
        footer_location: "مصر",
        footer_privacy: "سياسة الخصوصية",
        footer_terms: "شروط الخدمة",
        footer_rights: "جميع الحقوق محفوظة",

        // AI page
        ai_greeting: "كيف يمكنني مساعدتك؟",
        ai_greeting_sub: "اطرح سؤالك الطبي أو أرسل صورة للتشخيص الأولي",
        ai_new_chat: "محادثة جديدة",
        ai_recent: "الأخيرة",
        ai_disclaimer: "هذه الاستشارة إرشادية فقط",
        ai_footer: "مساعد ميدورا قد يرتكب أخطاء · استشر طبيبك في الحالات الحرجة",
        ai_placeholder: "اكتب رسالتك أو أرفق صورة…",
        ai_label: "مساعد ميدورا",
        ai_topbar: "مساعد ميدورا الطبي",
        ai_hide: "إخفاء القائمة",
        ai_show: "إظهار القائمة",
        ai_image_caption: "صورة مرفقة",
        ai_s1: "ما أعراض ارتفاع ضغط الدم؟",
        ai_s2: "كيف أتحكم في مستوى السكر؟",
        ai_s3: "متى يجب التوجه للطوارئ؟",
        ai_s4: "ما أسباب الإرهاق المستمر؟",
        ai_h1: "أعراض السكري",
        ai_h2: "ألم في الصدر",
        ai_h3: "دواء الضغط",
        ai_bot1: "شكراً على سؤالك! مساعد ميدورا الطبي قيد التطوير وسيكون متاحاً قريباً.",
        ai_bot2: "سؤال ممتاز. سيتعامل نموذجنا الذكي مع استفساراتك الطبية بدقة عالية في التحديث القادم.",
        ai_bot3: "نعمل على دمج أحدث نماذج الذكاء الاصطناعي الطبي. ترقّب التحديثات قريباً!",

        // Articles
        art_hero_title: "المقالات الطبية",
        art_hero_sub: "مكتبة شاملة من المقالات الطبية الموثوقة لتعزيز وعيك الصحي",
        art_search_ph: "ابحث عن مقال...",
        art_all: "الكل",
        art_read: "اقرأ المزيد",
        art_min: "دقيقة",
        art_load_more: "تحميل المزيد",
        art_no_results: "لا توجد مقالات مطابقة",
        art_breadcrumb_home: "الرئيسية",
        art_breadcrumb_articles: "المقالات",
        art_featured: "المقال المميز",
        art_all_articles: "جميع المقالات",
        art_new: "جديد",
        art_newsletter_title: "اشترك في النشرة الطبية",
        art_newsletter_sub: "احصل على أحدث المقالات والنصائح الطبية مباشرة في بريدك الإلكتروني",
        art_newsletter_ph: "أدخل بريدك الإلكتروني",
        art_newsletter_btn: "اشترك الآن",
        art_categories: ["كل المقالات", "الصحة العامة", "الصحة النفسية", "الأمراض والوقاية", "صحة الأطفال", "صحة وتغذية"],
        art_articles: [
            { id: 1, cat: "الصحة العامة", title: "أهمية شرب الماء للصحة العامة", excerpt: "الماء هو أساس الحياة ويلعب دوراً حيوياً في جميع وظائف الجسم. تعرف على الأهمية الحقيقية وفوائد شرب الماء بانتظام.", author: "د. أحمد محمود", date: "1 مارس 2026", readTime: 10, featured: true, imgKey: "water" },
            { id: 2, cat: "الصحة العامة", title: "كيف تحافظ على صحة قلبك؟", excerpt: "دليل شامل للحفاظ على صحة القلب والوقاية من الأمراض القلبية الشائعة.", author: "د. سارة أحمد", date: "25 فبراير 2026", readTime: 8, featured: false, imgKey: "nutrition" },
            { id: 3, cat: "صحة وتغذية", title: "التمارين الرياضية المناسبة للمبتدئين", excerpt: "ابدأ رحلتك الرياضية بأمان مع هذه التمارين المصممة خصيصاً للمبتدئين.", author: "د. خالد نور", date: "20 فبراير 2026", readTime: 6, featured: false, imgKey: "fitness" },
            { id: 4, cat: "الصحة النفسية", title: "إدارة التوتر والقلق في الحياة اليومية", excerpt: "تقنيات مجربة وفعالة لإدارة التوتر وتحسين الصحة النفسية في حياتك اليومية.", author: "د. ريم سليمان", date: "15 فبراير 2026", readTime: 7, featured: false, imgKey: "mental" },
            { id: 5, cat: "صحة الأطفال", title: "التغذية الصحية للأطفال في مرحلة النمو", excerpt: "كل ما تحتاج معرفته عن تغذية الأطفال السليمة خلال مراحل النمو المختلفة.", author: "د. نورا هاشم", date: "10 فبراير 2026", readTime: 5, featured: false, imgKey: "nutrition" },
            { id: 6, cat: "الأمراض والوقاية", title: "أهمية النوم الجيد للصحة العامة", excerpt: "تعرف على أهمية النوم الكافي وتأثيره على صحتك الجسدية والنفسية.", author: "د. سليم جابر", date: "5 فبراير 2026", readTime: 6, featured: false, imgKey: "mental" },
            { id: 7, cat: "الأمراض والوقاية", title: "الوقاية من مرض السكري من النوع الثاني", excerpt: "خطوات عملية ونصائح طبية فعالة للوقاية من الإصابة بمرض السكري.", author: "د. محمد علي", date: "1 فبراير 2026", readTime: 9, featured: false, imgKey: "water" },
            { id: 8, cat: "صحة وتغذية", title: "تمارين اليوغا لتحسين المرونة والتوازن", excerpt: "اكتشف فوائد اليوغا وأفضل التمارين لتحسين مرونة جسمك وتوازنك.", author: "د. لينا حسن", date: "25 يناير 2026", readTime: 5, featured: false, imgKey: "fitness" },
            { id: 9, cat: "الصحة النفسية", title: "الصحة النفسية لكبار السن", excerpt: "نصائح هامة للحفاظ على الصحة النفسية والعقلية في مراحل العمر المتقدمة.", author: "د. عمر فاروق", date: "20 يناير 2026", readTime: 7, featured: false, imgKey: "nutrition" },
        ],

        // Auth - Login
        login_title: "تسجيل الدخول",
        login_welcome: "مرحباً بعودتك! سجل دخولك للمتابعة",
        login_email: "البريد الإلكتروني",
        login_password: "كلمة المرور",
        login_remember: "تذكرني",
        login_forgot: "نسيت كلمة المرور؟",
        login_btn: "تسجيل الدخول",
        login_or: "أو",
        login_google: "التسجيل بـ Google",
        login_facebook: "التسجيل بـ Facebook",
        login_no_account: "ليس لديك حساب؟",
        login_create: "إنشاء حساب",
        or: "أو",
        login_err_both: "املأ البريد الإلكتروني وكلمة المرور",
        login_err_email: "املأ البريد الإلكتروني",
        login_err_pass: "املأ كلمة المرور",
        login_err_invalid: "كلمة المرور أو البريد الإلكتروني غير صحيح",

        // Auth - Register
        reg_title: "إنشاء حساب",
        reg_subtitle: "ملء البيانات إلزامي",
        reg_role_label: "اختر نوع الحساب",
        reg_pharmacy: "صيدلي",
        reg_doctor: "طبيب",
        reg_patient: "مريض",
        reg_fullname: "الاسم الكامل",
        reg_fullname_ph: "أدخل اسمك",
        reg_phone: "رقم الجوال",
        reg_email: "البريد الإلكتروني",
        reg_pass: "كلمة المرور",
        reg_confirm: "تأكيد كلمة المرور",
        reg_agree: "أوافق على",
        reg_terms: "شروط الخدمة",
        reg_and: "و",
        reg_privacy: "سياسة الخصوصية",
        reg_btn: "إنشاء حساب",
        reg_google: "إنشاء حساب بـ Google",
        reg_facebook: "إنشاء حساب بـ Facebook",
        reg_have_account: "لديك حساب بالفعل؟",
        reg_signin: "تسجيل الدخول",
        reg_err_name: "الاسم مطلوب",
        reg_err_phone: "رقم الجوال مطلوب",
        reg_err_email: "البريد الإلكتروني مطلوب",
        reg_err_email_invalid: "اكتب بريد صحيح",
        reg_err_email_exists: "هذا البريد الإلكتروني مسجل بالفعل",
        reg_err_email_unverified: "هذا البريد مسجل ولم يتم تأكيده بعد. يرجى تأكيد رمز التحقق.",
        reg_err_phone_exists: "رقم الهاتف مسجل بالفعل",
        reg_err_pass: "كلمة المرور مطلوبة",
        reg_err_confirm: "تأكيد كلمة المرور مطلوب",
        reg_err_match: "كلمتا المرور غير متطابقتين",
        reg_err_agree: "لازم توافق على الشروط والسياسة",

        // OTP
        otp_title: "التحقق بالرمز (OTP)",
        otp_sent: "تم إرسال رمز تحقق مكوّن من 6 أرقام إلى",
        otp_back: "الرجوع",
        otp_confirm: "التأكيد",
        otp_paste: "لصق الرمز",
        otp_resend: "إعادة الإرسال",
        otp_resend_in: "إعادة الإرسال خلال",
        otp_resend_success: "تم إرسال رمز جديد!",
        otp_expires_in: "الرمز صالح لـ",
        otp_expired: "انتهت صلاحية الرمز",
        otp_invalid: "الرمز غير صحيح أو منتهي الصلاحية",

        // CompleteDoctorProfile
        doc_profile_title: "استكمال بيانات الطبيب",
        doc_profile_sub: "الحقول المطلوبة إلزامية لتفعيل الحساب",
        doc_photo: "الصورة الشخصية",
        doc_optional: "(اختياري)",
        doc_upload_photo: "رفع صورة",
        doc_fullname: "الاسم بالكامل",
        doc_phone: "رقم الهاتف",
        doc_specialty: "التخصص",
        doc_bio: "نبذة تعريفية",
        doc_bio_ph: "اكتب نبذة مختصرة عنك وعن خبراتك...",
        doc_save: "حفظ وإكمال",
        doc_err_name: "الاسم بالكامل مطلوب",
        doc_err_specialty: "التخصص مطلوب",
        doc_err_license: "رقم الترخيص مطلوب",
        doc_err_phone: "رقم الهاتف مطلوب",
        doc_spec_select: "اختر",
        doc_license_label: "رقم الترخيص",
        doc_license_hint: "أدخل رقم ترخيص مزاولة المهنة الصادر من وزارة الصحة",
        doc_license_ph: "مثال: 12345678",
        doc_specialties: ["باطنة", "أطفال", "جلدية", "عظام", "نساء وتوليد", "أنف وأذن وحنجرة", "رمد", "قلب", "أسنان", "مخ وأعصاب", "جراحة عامة"],

        // CompletePharmacyProfile
        ph_title: "استكمال بيانات الصيدلي",
        ph_sub: "املأ بيانات الصيدلية لتفعيل الحساب",
        ph_photo: "صورة الصيدلية",
        ph_optional: "(اختياري)",
        ph_upload_photo: "رفع صورة",
        ph_name: "اسم الصيدلية",
        ph_license: "رقم الترخيص",
        ph_governorate: "المحافظة",
        ph_governorate_ph: "اختر المحافظة",
        ph_city: "المدينة / المنطقة",
        ph_city_ph: "اختر المدينة",
        ph_phone: "رقم الهاتف",
        ph_address: "العنوان التفصيلي",
        ph_bio: "وصف الصيدلية",
        ph_bio_ph: "اكتب نبذة عن خدمات الصيدلية...",
        ph_open24: "هل الصيدلية مفتوحة 24 ساعة؟",
        ph_yes: "نعم",
        ph_no: "لا",
        ph_open_from: "وقت الفتح",
        ph_open_to: "وقت الإغلاق",
        ph_save: "حفظ وإكمال",
        ph_err_name: "اسم الصيدلية مطلوب",
        ph_err_license: "رقم الترخيص مطلوب",
        ph_err_governorate: "اختر المحافظة",
        ph_err_city: "اختر المدينة",
        ph_err_phone: "رقم الهاتف مطلوب",
        ph_err_address: "العنوان مطلوب",
        ph_governorates: ["القاهرة", "الجيزة", "الإسكندرية", "الدقهلية", "البحيرة", "الشرقية", "الغربية", "المنوفية", "القليوبية", "كفر الشيخ", "دمياط", "بورسعيد", "الإسماعيلية", "السويس", "الفيوم", "بني سويف", "المنيا", "أسيوط", "سوهاج", "قنا", "الأقصر", "أسوان", "البحر الأحمر", "الوادي الجديد", "مطروح", "شمال سيناء", "جنوب سيناء"],
        ph_cities: {
            "القاهرة": ["النزهة", "مدينة نصر", "المعادي", "حلوان", "المطرية", "عين شمس", "شبرا", "الزيتون", "مصر الجديدة", "الدقي", "السلام", "المقطم", "التجمع الخامس", "الشروق", "بدر", "العبور", "15 مايو", "القطامية", "المرج", "عزبة النخل"],
            "الجيزة": ["الجيزة", "الدقي", "العجوزة", "المهندسين", "إمبابة", "بولاق الدكرور", "الهرم", "فيصل", "الشيخ زايد", "أكتوبر", "البدرشين", "الحوامدية", "أبو النمرس", "الواحات البحرية"],
            "الإسكندرية": ["المنتزه", "العجمي", "الدخيلة", "سيدي جابر", "سموحة", "محرم بك", "العامرية", "الرمل", "وابور المياه", "بحري", "غرب الإسكندرية"],
            "الدقهلية": ["المنصورة", "طلخا", "المنزلة", "الزقازيق", "ميت غمر", "دكرنس", "أجا", "السنبلاوين", "شربين", "بلقاس", "منية النصر"],
            "البحيرة": ["دمنهور", "كفر الدوار", "رشيد", "إيتاي البارود", "أبو حمص", "الدلنجات", "المحمودية", "حوش عيسى", "شبراخيت", "بدر"],
            "الشرقية": ["الزقازيق", "بلبيس", "ميت أبو علي", "فاقوس", "منيا القمح", "أبو كبير", "الإبراهيمية", "ههيا", "أبو حماد", "القنايات"],
            "الغربية": ["طنطا", "المحلة الكبرى", "كفر الزيات", "زفتى", "السنطة", "قطور", "بسيون"],
            "المنوفية": ["شبين الكوم", "مينوف", "أشمون", "السادات", "قويسنا", "طلا", "برج العرب"],
            "القليوبية": ["بنها", "قليوب", "شبرا الخيمة", "العبور", "طوخ", "الخانكة", "كفر شكر", "الخصوص"],
            "كفر الشيخ": ["كفر الشيخ", "سيدي سالم", "دسوق", "فوه", "مطوبس", "بيلا", "الرياض", "برلس"],
            "دمياط": ["دمياط", "رأس البر", "الزرقا", "فارسكور", "كفر سعد"],
            "بورسعيد": ["بورسعيد", "بور فؤاد", "المنطقة الحرة"],
            "الإسماعيلية": ["الإسماعيلية", "القنطرة شرق", "القنطرة غرب", "فايد", "التل الكبير", "أبو صوير"],
            "السويس": ["السويس", "عتاقة", "الجناين", "فيصل"],
            "الفيوم": ["الفيوم", "سنورس", "طامية", "يوسف الصديق", "إطسا", "إبشواي"],
            "بني سويف": ["بني سويف", "الواسطي", "ناصر", "إهناسيا", "ببا", "الفشن", "سمسطا"],
            "المنيا": ["المنيا", "مغاغة", "مطاي", "بني مزار", "سمالوط", "ملوي", "أبو قرقاص", "العدوة", "دير مواس"],
            "أسيوط": ["أسيوط", "ديروط", "القوصية", "أبنوب", "الغنايم", "منفلوط", "صدفا", "ساحل سليم"],
            "سوهاج": ["سوهاج", "جرجا", "أخميم", "طهطا", "المراغة", "دار السلام", "جهينة", "البلينا", "المنشأة"],
            "قنا": ["قنا", "نجع حمادي", "أبو تشت", "قوص", "الوقف", "دشنا", "فرشوط"],
            "الأقصر": ["الأقصر", "الزينية", "إسنا", "الطود", "أرمنت", "البياضية", "القرنة"],
            "أسوان": ["أسوان", "كوم أمبو", "إدفو", "نصر النوبة", "دراو", "أبو سمبل", "إسناو"],
            "البحر الأحمر": ["الغردقة", "سفاجا", "القصير", "مرسى علم", "شرم الشيخ", "رأس غارب"],
            "الوادي الجديد": ["الخارجة", "الداخلة", "الفرافرة", "بلاط"],
            "مطروح": ["مرسى مطروح", "سيوة", "الضبعة", "سيدي براني", "السلوم", "العلمين"],
            "شمال سيناء": ["العريش", "الشيخ زويد", "رفح", "بئر العبد", "الحسنة", "نخل"],
            "جنوب سيناء": ["طور سيناء", "شرم الشيخ", "دهب", "نويبع", "سانت كاترين", "أبو زنيمة"]
        },

        // CompleteDoctorVerification
        ver_title: "التحقق من هوية الطبيب",
        ver_sub: "يرجى رفع المستندات المطلوبة للتحقق من بياناتك",
        ver_step1: "بيانات النقابة",
        ver_step2: "السيلفي",
        ver_step3: "الترخيص",
        ver_card_label: "صورة بطاقة النقابة",
        ver_card_hint: "ارفع صورة واضحة لبطاقة نقابة الأطباء الخاصة بك",
        ver_selfie_label: "سيلفي مع بطاقة النقابة",
        ver_selfie_hint: "التقط صورة لوجهك وأنت تمسك بطاقة النقابة بوضوح",
        ver_license_label: "رقم الترخيص",
        ver_license_hint: "أدخل رقم ترخيص مزاولة المهنة الصادر من وزارة الصحة",
        ver_license_ph: "مثال: 12345678",
        ver_upload: "اضغط لرفع الصورة",
        ver_uploaded: "✓ تم الرفع",
        ver_submit: "إرسال للمراجعة",
        ver_review_note: "ستتم مراجعة بياناتك خلال 24-48 ساعة بعد الإرسال",
        ver_err_card: "صورة بطاقة النقابة مطلوبة",
        ver_err_selfie: "السيلفي مع بطاقة النقابة مطلوب",
        ver_err_license: "رقم الترخيص مطلوب",

        // ForgotPassword
        forgot_brand: "ميدورا",
        forgot_title: "هل نسيت كلمة المرور؟",
        forgot_sub: "ادخل بريدك الإلكتروني لتحصل على رسالة رمز التحقق لإعادة تعيين كلمة المرور",
        forgot_label: "البريد الإلكتروني",
        forgot_ph: "example@mail.com",
        forgot_send: "إرسال رمز التحقق",
        forgot_back: "الرجوع لتسجيل الدخول",
        forgot_err_empty: "اكتب البريد الإلكتروني",

        // ResetPassword
        reset_brand: "ميدورا",
        reset_title: "تعيين كلمة مرور جديدة",
        reset_sub: "اكتب كلمة مرور جديدة للحساب:",
        reset_new_pass: "كلمة المرور الجديدة",
        reset_confirm_pass: "تأكيد كلمة المرور",
        reset_req_title: "متطلبات كلمة المرور:",
        reset_req_min: "لا يقل عن 6 أحرف",
        reset_req_upper: "يحتوي على حرف كبير (A-Z)",
        reset_req_lower: "يحتوي على حرف صغير (a-z)",
        reset_req_number: "يحتوي على رقم (0-9)",
        reset_req_special: "يحتوي على رمز خاص (!@#$%^&*)",
        reset_match: "كلمتا المرور متطابقتان",
        reset_no_match: "كلمتا المرور غير متطابقتين",
        reset_err_req: "يرجى استيفاء جميع متطلبات كلمة المرور",
        reset_back: "رجوع",
        reset_save: "حفظ كلمة المرور",
        reset_signin: "الرجوع لتسجيل الدخول",
    },

    en: {
        dir: "ltr",
        // Navbar
        nav_home: "Home",
        nav_doctors: "Doctors",
        nav_ai: "AI Consultation",
        nav_pharmacy: "Pharmacy",
        nav_articles: "Articles",
        nav_contact: "Contact",
        nav_login: "Sign In",
        nav_register: "Sign Up",
        brand: "Medora",

        // Hero
        hero_title: "Medora — Your Complete Medical Platform",
        hero_subtitle: "Book appointments with top doctors, find medicines, and get instant medical consultations.",
        hero_start: "Get Started",
        hero_learn: "Learn More",
        hero_card1_title: "AI Consultations",
        hero_card1_desc: "Instant medical advice available 24/7",
        hero_card2_title: "Trusted Pharmacies",
        hero_card2_desc: "A wide network of certified pharmacies",
        hero_card3_title: "Certified Doctors",
        hero_card3_desc: "Over 500 doctors across all specialties",
        hero_card4_title: "Medical Articles",
        hero_card4_desc: "Simple health content to help you make better decisions",

        // Services
        services_title: "Our Integrated Medical Services",
        services_sub: "We provide a comprehensive suite of digital medical services to ease your healthcare journey.",
        services_learnmore: "Learn more →",
        svc1_title: "Book Appointment", svc1_desc: "Book your appointments with doctors easily and quickly",
        svc2_title: "AI Consultation", svc2_desc: "Get instant medical advice powered by AI",
        svc3_title: "Find Medicine", svc3_desc: "Search for medicines and nearby pharmacies",
        svc4_title: "Find a Doctor", svc4_desc: "Find the best doctors across different specialties",
        service_hub_seo_title: "Services",
        service_hub_seo_description: "Explore Medora services: doctors, medicines, pharmacies, AI consultation, and trusted health articles.",
        service_hub_badge: "All your medical services in one place",
        service_hub_title: "Choose the medical service you need now",
        service_hub_subtitle: "Move quickly between doctor booking, medicine search, nearby pharmacies, AI consultation, and reliable medical content.",
        service_hub_section_title: "Medora Services",
        service_hub_available: "Available",
        service_hub_doctor_title: "Doctors & Appointments",
        service_hub_doctor_desc: "Find the right doctor by specialty and location, then book your visit in a few simple steps.",
        service_hub_doctor_action: "Find a doctor",
        service_hub_medicine_title: "Medicine Search",
        service_hub_medicine_desc: "Review medicine details, alternatives, warnings, and options for getting what you need.",
        service_hub_medicine_action: "Find medicine",
        service_hub_pharmacy_title: "Nearby Pharmacies",
        service_hub_pharmacy_desc: "Browse available pharmacies near you and check medicine availability, pickup, or delivery options.",
        service_hub_pharmacy_action: "Browse pharmacies",
        service_hub_ai_title: "AI Consultation",
        service_hub_ai_desc: "Ask health questions and get initial guidance to better understand your next step.",
        service_hub_ai_action: "Start consultation",
        service_hub_articles_title: "Medical Articles",
        service_hub_articles_desc: "Read simple health articles about prevention, daily habits, and medical care.",
        service_hub_articles_action: "Read articles",
        service_hub_guide_title: "Not sure where to start?",
        service_hub_guide_subtitle: "Choose the closest situation and we will guide you to the best path inside Medora.",
        service_hub_guide_symptoms_title: "You have symptoms and need a doctor",
        service_hub_guide_symptoms_desc: "Start by searching for a doctor by specialty or area and book the nearest appointment.",
        service_hub_guide_medicine_title: "You are looking for medicine or an alternative",
        service_hub_guide_medicine_desc: "Use search to view medicine details and pharmacies that provide it.",
        service_hub_guide_question_title: "You have a quick medical question",
        service_hub_guide_question_desc: "Use AI consultation for initial guidance before visiting a doctor.",
        service_hub_emergency_title: "Important notice",
        service_hub_emergency_desc: "For emergencies or serious symptoms, contact emergency services or go to the nearest hospital immediately. Medora services do not replace urgent care.",

        // HowItWorks
        how_title: "How does Medora work?",
        how_sub: "Four simple steps to get the medical care you need",
        step1_title: "Create Account", step1_desc: "Register as a patient, doctor, or pharmacist in minutes",
        step2_title: "Search & Choose", step2_desc: "Find the right doctor or the medicine you need",
        step3_title: "Book Your Visit", step3_desc: "Book your medical appointments easily and get instant confirmation",
        step4_title: "Receive Care", step4_desc: "Enjoy a premium and safe medical service",

        // Stats
        stats_title: "Our Numbers Speak for Themselves",
        stats_sub: "We are proud of the trust thousands of users place in our distinguished medical services.",
        stat1_label: "Successful appointments",
        stat2_label: "Satisfied users",
        stat3_label: "Trusted pharmacies",
        stat4_label: "Certified doctors",

        // Testimonials
        test_title: "What Our Clients Say",
        test_sub: "Real reviews from our valued users about their experience with Medora",
        t1_name: "Saif Wagid", t1_role: "User",
        t1_text: "An amazing platform that makes booking doctor appointments easy. Excellent service and very user-friendly app.",
        t2_name: "Malak Mohamed", t2_role: "Pediatrician",
        t2_text: "Medora has helped me a lot in organizing my schedule and communicating with patients better. An indispensable tool.",
        t3_name: "Dr. Khaled Ahmed", t3_role: "Manager",
        t3_text: "The booking systems and data management are excellent, and customer communication is great. Our sales grew significantly.",

        // CTA
        cta_title: "Start Your Health Journey Today",
        cta_sub: "Join thousands of users who trust Medora for the best medical care.",
        cta_login: "Sign In",
        cta_register: "Sign Up",

        // Footer
        footer_desc: "Your comprehensive medical platform for the best digital healthcare.",
        footer_quick: "Quick Links",
        footer_home: "Home",
        footer_find_doctor: "Find a Doctor",
        footer_find_medicine: "Find Medicine",
        footer_ai: "AI Consultation",
        footer_users: "For Users",
        footer_reg_patient: "Sign Up (Patient)",
        footer_reg_doctor: "Sign Up (Doctor)",
        footer_reg_pharmacy: "Sign Up (Pharmacist)",
        footer_login: "Sign In",
        footer_contact: "Contact Us",
        footer_location: "Egypt",
        footer_privacy: "Privacy Policy",
        footer_terms: "Terms of Service",
        footer_rights: "All Rights Reserved",

        // AI page
        ai_greeting: "How can I help you?",
        ai_greeting_sub: "Ask your medical question or send an image for an initial assessment",
        ai_new_chat: "New Chat",
        ai_recent: "Recent",
        ai_disclaimer: "This consultation is for guidance only",
        ai_footer: "Medora's assistant may make mistakes · Consult your doctor in critical cases",
        ai_placeholder: "Type your message or attach an image…",
        ai_label: "Medora Assistant",
        ai_topbar: "Medora Medical Assistant",
        ai_hide: "Hide Sidebar",
        ai_show: "Show Sidebar",
        ai_image_caption: "Attached image",
        ai_s1: "What are symptoms of high blood pressure?",
        ai_s2: "How do I control my blood sugar?",
        ai_s3: "When should I go to the emergency room?",
        ai_s4: "What causes constant fatigue?",
        ai_h1: "Diabetes symptoms",
        ai_h2: "Chest pain",
        ai_h3: "Blood pressure meds",
        ai_bot1: "Thank you for your question! Medora's medical assistant is under development and will be available soon.",
        ai_bot2: "Great question. Our AI model will handle your medical inquiries with high accuracy in the next update.",
        ai_bot3: "We are working on integrating the latest medical AI models. Stay tuned for updates!",

        // Articles
        art_hero_title: "Medical Articles",
        art_hero_sub: "A comprehensive library of trusted medical articles to boost your health awareness",
        art_search_ph: "Search articles...",
        art_all: "All",
        art_read: "Read More",
        art_min: "min",
        art_load_more: "Load More",
        art_no_results: "No matching articles found",
        art_breadcrumb_home: "Home",
        art_breadcrumb_articles: "Articles",
        art_featured: "Featured Article",
        art_all_articles: "All Articles",
        art_new: "New",
        art_newsletter_title: "Subscribe to Our Medical Newsletter",
        art_newsletter_sub: "Get the latest articles and medical tips delivered directly to your inbox",
        art_newsletter_ph: "Enter your email",
        art_newsletter_btn: "Subscribe Now",
        art_categories: ["All Articles", "General Health", "Mental Health", "Diseases & Prevention", "Children's Health", "Health & Nutrition"],
        art_articles: [
            { id: 1, cat: "General Health", title: "The Importance of Drinking Water for General Health", excerpt: "Water is the essence of life and plays a vital role in all body functions. Learn about the real importance and benefits of drinking water regularly.", author: "Dr. Ahmed Mahmoud", date: "Mar 1, 2026", readTime: 10, featured: true, imgKey: "water" },
            { id: 2, cat: "General Health", title: "How to Maintain Your Heart Health?", excerpt: "A comprehensive guide to maintaining heart health and preventing common cardiovascular diseases.", author: "Dr. Sara Ahmed", date: "Feb 25, 2026", readTime: 8, featured: false, imgKey: "nutrition" },
            { id: 3, cat: "Health & Nutrition", title: "Suitable Exercises for Beginners", excerpt: "Start your fitness journey safely with these exercises designed specifically for beginners.", author: "Dr. Khaled Nour", date: "Feb 20, 2026", readTime: 6, featured: false, imgKey: "fitness" },
            { id: 4, cat: "Mental Health", title: "Managing Stress and Anxiety in Daily Life", excerpt: "Proven and effective techniques for managing tension and improving mental wellbeing in your daily life.", author: "Dr. Reem Soliman", date: "Feb 15, 2026", readTime: 7, featured: false, imgKey: "mental" },
            { id: 5, cat: "Children's Health", title: "Healthy Nutrition for Children During Growth", excerpt: "Everything you need to know about proper children's nutrition during different growth stages.", author: "Dr. Noura Hashem", date: "Feb 10, 2026", readTime: 5, featured: false, imgKey: "nutrition" },
            { id: 6, cat: "Diseases & Prevention", title: "The Importance of Good Sleep for General Health", excerpt: "Learn about the importance of adequate sleep and its impact on your physical and mental health.", author: "Dr. Salim Jaber", date: "Feb 5, 2026", readTime: 6, featured: false, imgKey: "mental" },
            { id: 7, cat: "Diseases & Prevention", title: "Preventing Type 2 Diabetes", excerpt: "Practical steps and effective medical tips to prevent developing diabetes.", author: "Dr. Mohamed Ali", date: "Feb 1, 2026", readTime: 9, featured: false, imgKey: "water" },
            { id: 8, cat: "Health & Nutrition", title: "Yoga Exercises for Flexibility and Balance", excerpt: "Discover the benefits of yoga and the best exercises to improve your body's flexibility and balance.", author: "Dr. Lina Hassan", date: "Jan 25, 2026", readTime: 5, featured: false, imgKey: "fitness" },
            { id: 9, cat: "Mental Health", title: "Mental Health for the Elderly", excerpt: "Important tips for maintaining mental and cognitive health in advanced stages of life.", author: "Dr. Omar Farouk", date: "Jan 20, 2026", readTime: 7, featured: false, imgKey: "nutrition" },
        ],

        // Auth - Login
        login_title: "Sign In",
        login_welcome: "Welcome back! Sign in to continue",
        login_email: "Email Address",
        login_password: "Password",
        login_remember: "Remember me",
        login_forgot: "Forgot password?",
        login_btn: "Sign In",
        login_or: "or",
        login_google: "Sign in with Google",
        login_facebook: "Sign in with Facebook",
        login_no_account: "Don't have an account?",
        login_create: "Sign Up",
        or: "or",
        login_err_both: "Please enter your email and password",
        login_err_email: "Please enter your email",
        login_err_pass: "Please enter your password",
        login_err_invalid: "Invalid email or password",

        // Auth - Register
        reg_title: "Create Account",
        reg_subtitle: "All fields are required",
        reg_role_label: "Select account type",
        reg_pharmacy: "Pharmacist",
        reg_doctor: "Doctor",
        reg_patient: "Patient",
        reg_fullname: "Full Name",
        reg_fullname_ph: "Enter your name",
        reg_phone: "Phone Number",
        reg_email: "Email Address",
        reg_pass: "Password",
        reg_confirm: "Confirm Password",
        reg_agree: "I agree to the",
        reg_terms: "Terms of Service",
        reg_and: "and",
        reg_privacy: "Privacy Policy",
        reg_btn: "Create Account",
        reg_google: "Sign up with Google",
        reg_facebook: "Sign up with Facebook",
        reg_have_account: "Already have an account?",
        reg_signin: "Sign In",
        reg_err_name: "Full name is required",
        reg_err_phone: "Phone number is required",
        reg_err_email: "Email is required",
        reg_err_email_invalid: "Enter a valid email",
        reg_err_email_exists: "This email is already registered",
        reg_err_email_unverified: "This email is registered but not verified yet. Please confirm the verification code.",
        reg_err_phone_exists: "This phone number is already registered",
        reg_err_pass: "Password is required",
        reg_err_confirm: "Please confirm your password",
        reg_err_match: "Passwords do not match",
        reg_err_agree: "You must agree to the terms and policy",

        // OTP
        otp_title: "OTP Verification",
        otp_sent: "A 6-digit verification code was sent to",
        otp_back: "Go Back",
        otp_confirm: "Confirm",
        otp_paste: "Paste Code",
        otp_resend: "Resend Code",
        otp_resend_in: "Resend in",
        otp_resend_success: "A new code was sent!",
        otp_expires_in: "Code expires in",
        otp_expired: "Code Expired",
        otp_invalid: "Invalid or expired code",

        // CompleteDoctorProfile
        doc_profile_title: "Complete Doctor Profile",
        doc_profile_sub: "Required fields are mandatory to activate your account",
        doc_photo: "Profile Photo",
        doc_optional: "(optional)",
        doc_upload_photo: "Upload photo",
        doc_fullname: "Full Name",
        doc_phone: "Phone Number",
        doc_specialty: "Specialty",
        doc_bio: "Short Bio",
        doc_bio_ph: "Write a brief introduction about yourself and your experience...",
        doc_save: "Save & Continue",
        doc_err_name: "Full name is required",
        doc_err_specialty: "Specialty is required",
        doc_err_license: "License number is required",
        doc_err_phone: "Phone number is required",
        doc_spec_select: "Select",
        doc_license_label: "License Number",
        doc_license_hint: "Enter your professional practice license number issued by the Ministry of Health",
        doc_license_ph: "e.g. 12345678",
        doc_specialties: ["Internal Medicine", "Pediatrics", "Dermatology", "Orthopedics", "Gynecology", "ENT", "Ophthalmology", "Cardiology", "Dentistry", "Neurology", "General Surgery"],

        // CompletePharmacyProfile
        ph_title: "Complete Pharmacy Profile",
        ph_sub: "Fill in your pharmacy details to activate the account",
        ph_photo: "Pharmacy Photo",
        ph_optional: "(optional)",
        ph_upload_photo: "Upload Photo",
        ph_name: "Pharmacy Name",
        ph_license: "License Number",
        ph_governorate: "Governorate",
        ph_governorate_ph: "Select Governorate",
        ph_city: "City / District",
        ph_city_ph: "Select City",
        ph_phone: "Phone Number",
        ph_address: "Detailed Address",
        ph_bio: "Pharmacy Description",
        ph_bio_ph: "Write a short description of your pharmacy services...",
        ph_open24: "Is the pharmacy open 24 hours?",
        ph_yes: "Yes",
        ph_no: "No",
        ph_open_from: "Opening Time",
        ph_open_to: "Closing Time",
        ph_save: "Save & Continue",
        ph_err_name: "Pharmacy name is required",
        ph_err_license: "License number is required",
        ph_err_governorate: "Please select a governorate",
        ph_err_city: "Please select a city",
        ph_err_phone: "Phone number is required",
        ph_err_address: "Address is required",
        ph_governorates: ["Cairo", "Giza", "Alexandria", "Dakahlia", "Beheira", "Sharqia", "Gharbia", "Monufia", "Qalyubia", "Kafr el-Sheikh", "Damietta", "Port Said", "Ismailia", "Suez", "Faiyum", "Beni Suef", "Minya", "Asyut", "Sohag", "Qena", "Luxor", "Aswan", "Red Sea", "New Valley", "Matrouh", "North Sinai", "South Sinai"],
        ph_cities: {
            "Cairo": ["Nasr City", "Maadi", "Helwan", "Matariya", "Ain Shams", "Shubra", "Zeitoun", "New Cairo", "Dokki", "El-Salam", "Moqattam", "Fifth Settlement", "El-Shorouk", "Badr", "El-Obour", "15th of May", "El-Qattamiya", "El-Marg", "Ezbet El-Nakhl"],
            "Giza": ["Giza", "Dokki", "Agouza", "Mohandessin", "Imbaba", "Boulaq El-Dakrour", "Haram", "Faisal", "Sheikh Zayed", "October", "Badrashein", "Hawamdia", "Abu El-Nomros", "Bahria Oasis"],
            "Alexandria": ["Montazah", "Agami", "Dekheila", "Sidi Gaber", "Smouha", "Moharam Bek", "Ameriya", "Raml", "Wapur", "Bahri", "West Alexandria"],
            "Dakahlia": ["Mansoura", "Talkha", "El-Manzala", "Zaqaziq", "Mit Ghamr", "Dekernes", "Aga", "Sinbillawin", "Sherbin", "Belqas", "Menia El-Nasr"],
            "Beheira": ["Damanhur", "Kafr El-Dawar", "Rashid", "Itay El-Baroud", "Abu Homs", "El-Delengat", "Mahmoudiya", "Hosh Issa", "Shubrakhit", "Badr"],
            "Sharqia": ["Zagazig", "Bilbeis", "Mit Abu Ali", "Faqous", "Minya El-Qamh", "Abu Kebir", "El-Ibrahimiya", "Hihya", "Abu Hammad", "El-Qanayat"],
            "Gharbia": ["Tanta", "Mahalla El-Kubra", "Kafr El-Zayat", "Zifta", "El-Santa", "Qutour", "Basyoun"],
            "Monufia": ["Shibin El-Kom", "Minouf", "Ashmoun", "El-Sadat", "Quesna", "Tala", "Borg El-Arab"],
            "Qalyubia": ["Benha", "Qalyub", "Shubra El-Kheima", "El-Obour", "Toukh", "El-Khanka", "Kafr Shukr", "El-Khosous"],
            "Kafr el-Sheikh": ["Kafr El-Sheikh", "Sidi Salem", "Desouk", "Fuwwa", "Mutubis", "Bila", "El-Riyad", "Burullus"],
            "Damietta": ["Damietta", "Ras El-Bar", "El-Zarqa", "Faraskour", "Kafr Saad"],
            "Port Said": ["Port Said", "Port Fouad", "Free Zone"],
            "Ismailia": ["Ismailia", "El-Qantara East", "El-Qantara West", "Fayed", "El-Tal El-Kebir", "Abu Suwer"],
            "Suez": ["Suez", "Ataka", "El-Ganayen", "Faisal"],
            "Faiyum": ["Faiyum", "Sinnoures", "Tamiya", "Yusuf El-Seddiq", "Etsa", "Ibshway"],
            "Beni Suef": ["Beni Suef", "El-Wasta", "Nasser", "Ihnasya", "Beba", "El-Fashn", "Sumusta"],
            "Minya": ["Minya", "Maghagha", "Matay", "Beni Mazar", "Samalut", "Mallawi", "Abu Qirqas", "El-Adwa", "Deir Mawas"],
            "Asyut": ["Asyut", "Dayrut", "El-Qusiya", "Abnub", "El-Ghanayem", "Manfalut", "Sedfa", "Sahel Selim"],
            "Sohag": ["Sohag", "Gerga", "Akhmim", "Tahta", "El-Maragha", "Dar El-Salam", "Juhayna", "El-Balyana", "El-Mansha"],
            "Qena": ["Qena", "Nag Hammadi", "Abu Tesht", "Qus", "El-Waqf", "Dishna", "Farshut"],
            "Luxor": ["Luxor", "El-Zainiya", "Esna", "El-Tod", "Armant", "El-Bayadiya", "El-Qurna"],
            "Aswan": ["Aswan", "Kom Ombo", "Edfu", "Nasr El-Nuba", "Daraw", "Abu Simbel", "Isnaw"],
            "Red Sea": ["Hurghada", "Safaga", "El-Quseir", "Marsa Alam", "El-Shalatin", "Ras Ghareb"],
            "New Valley": ["El-Kharga", "El-Dakhla", "El-Farafra", "Balat"],
            "Matrouh": ["Marsa Matrouh", "Siwa", "El-Dabaa", "Sidi Barrani", "El-Sallum", "El-Alamein"],
            "North Sinai": ["El-Arish", "Sheikh Zuweid", "Rafah", "Bir El-Abd", "El-Hasna", "Nakhl"],
            "South Sinai": ["Tor Sinai", "Sharm El-Sheikh", "Dahab", "Nuweiba", "Saint Catherine", "Abu Zenima"]
        },

        // CompleteDoctorVerification
        ver_title: "Doctor Identity Verification",
        ver_sub: "Please upload the required documents to verify your identity",
        ver_step1: "Syndicate Card",
        ver_step2: "Selfie",
        ver_step3: "License",
        ver_card_label: "Syndicate Card Photo",
        ver_card_hint: "Upload a clear photo of your medical syndicate card",
        ver_selfie_label: "Selfie with Syndicate Card",
        ver_selfie_hint: "Take a photo of your face while holding the syndicate card clearly",
        ver_license_label: "License Number",
        ver_license_hint: "Enter your professional practice license number issued by the Ministry of Health",
        ver_license_ph: "e.g. 12345678",
        ver_upload: "Click to upload image",
        ver_uploaded: "✓ Uploaded",
        ver_submit: "Submit for Review",
        ver_review_note: "Your data will be reviewed within 24–48 hours after submission",
        ver_err_card: "Syndicate card photo is required",
        ver_err_selfie: "Selfie with syndicate card is required",
        ver_err_license: "License number is required",

        // ForgotPassword
        forgot_brand: "Medora",
        forgot_title: "Forgot Your Password?",
        forgot_sub: "Enter your email to receive a verification code to reset your password.",
        forgot_label: "Email",
        forgot_ph: "example@mail.com",
        forgot_send: "Send Verification Code",
        forgot_back: "Back to Sign In",
        forgot_err_empty: "Please enter your email",

        // ResetPassword
        reset_brand: "Medora",
        reset_title: "Set a New Password",
        reset_sub: "Enter a new password for the account:",
        reset_new_pass: "New Password",
        reset_confirm_pass: "Confirm Password",
        reset_req_title: "Password requirements:",
        reset_req_min: "At least 6 characters",
        reset_req_upper: "Contains an uppercase letter (A-Z)",
        reset_req_lower: "Contains a lowercase letter (a-z)",
        reset_req_number: "Contains a number (0-9)",
        reset_req_special: "Contains a special character (!@#$%^&*)",
        reset_match: "Passwords match",
        reset_no_match: "Passwords do not match",
        reset_err_req: "Please meet all password requirements",
        reset_back: "Go Back",
        reset_save: "Save Password",
        reset_signin: "Back to Sign In",
    },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
    const { i18n } = useTranslation();
    const lang = i18n.resolvedLanguage === "en" ? "en" : "ar";

    const t = useMemo(() => translations[lang] ?? translations.ar, [lang]);

    const toggleLang = useCallback(() => {
        const nextLang = lang === "ar" ? "en" : "ar";
        void i18n.changeLanguage(nextLang);
        void import("../utils/languagePreference").then(({ syncLanguageToServer }) => {
            void syncLanguageToServer(nextLang);
        });
    }, [i18n, lang]);

    const value = useMemo(() => ({ lang, t, toggleLang }), [lang, t, toggleLang]);

    return (
        <LanguageContext.Provider value={value}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLang() {
    const context = useContext(LanguageContext);

    if (!context) {
        throw new Error("useLang must be used within LanguageProvider");
    }

    return context;
}
