// <auto-generated />
using Medora.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Medora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625133000_AddPreferredLanguageAndMedicineReviewTarget")]
    partial class AddPreferredLanguageAndMedicineReviewTarget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
#pragma warning restore 612, 618
        }
    }
}
